#Build stage
FROM golang:1.11 as builder

#RUN mkdir /builder

ADD . /build/

WORKDIR /build
RUN CGO_ENABLED=0 go build -o redit-bot .
RUN pwd
RUN ["ls", "-l"]

#Final image
FROM golang:alpine
RUN apk add --no-cache bash
#RUN adduser -S -D -H -h /app appuser
#USER appuser
WORKDIR /app
COPY --from=builder /build/redit-bot /app/
RUN mkdir config
#RUN ["./redit-bot"]
ENTRYPOINT ["./redit-bot", "pull"]

